### ISSUE TITLE
Why is this broken?

### ISSUE THREAD

**Issue by hharchani** [felicity-iiith/felicity16-website#199]
![screenshot from 2017-01-20 00-52-59](https://cloud.githubusercontent.com/assets/6430611/22121692/0066ec4e-deab-11e6-8f9d-8f73c88eccbe.png)

**Comment by hharchani** [comment]
@saganshul @mukulhase @pinkeshbadjatiya

**Comment by hharchani** [comment]
https://felicity.iiit.ac.in/16/about/

**Comment by saganshul** [comment]
@hharchani Actually it was my mistake. I was using FelicityJuggad'16 of Shana while working on Felicity'17 website.
Fixed!
