### ISSUE TITLE
Set up MinimvalMVC

### ISSUE THREAD

**Issue by polybuildr** [felicity-iiith/felicity16-website#23]
Pick an implementation: `cp` if `git submodule` isn't doing the job, or whatever. After picking, implement in repo.

**Comment by nisargjhaveri** [comment]
I believe minimalMVC is perfectly set up as submodule.

**Comment by polybuildr** [comment]
Weren't there issues with sticking to a particular tag or branch?

**Comment by nisargjhaveri** [comment]
Looks fine as of now. Will rethink if something comes up again.
