### ISSUE TITLE
JSHint CLI does not return error status code on fail

### ISSUE THREAD

**Issue by polybuildr** [felicity-iiith/felicity16-website#28]
As you can see at https://travis-ci.org/felicity-iiith/felicity16/builds/82419533#L235, JSHint failing does not fail the build. We need a `fail` reporter (something that `gulp-jshint` provides) but _may_ have to write it ourselves.

Or this might just be an upstream issue.

**Comment by polybuildr** [comment]
But it failed at https://travis-ci.org/felicity-iiith/felicity16/builds/72113013. I'm confused :cry:

**Comment by nisargjhaveri** [comment]
Does it still do that?

**Comment by polybuildr** [comment]
Nah. This was fixed in d9e8c8e (#36, which you merged, coincidentally :P).

Sorry, forgot to close the issue here. It was tracked as http://phab.felicity.iiit.ac.in/T45.
